from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class VerifierSpec:
    """Defines how to check whether a task was solved."""

    kind: str  # e.g., "python_assert", "expected_number", "unit_test"
    spec: Dict[str, Any]


@dataclass
class TaskSpec:
    """Task payload generated by the teacher."""

    task_id: str
    domain: str  # e.g., "math", "logic", "code"
    prompt: str
    constraints: List[str] = field(default_factory=list)
    verifier: Optional[VerifierSpec] = None
    seed: Optional[int] = None


@dataclass
class Trajectory:
    """Stores the full interaction for replay or fine-tuning."""

    task: TaskSpec
    messages: List[Dict[str, Any]]
    tool_calls: List[Dict[str, Any]]
    result: str
    success: bool
    reward: Dict[str, float]
    metrics: Dict[str, float] = field(default_factory=dict)
